# Generated by Django 4.1.5 on 2023-02-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
    ]

    operations = []
